log_level = "warn"
position = "Top"

[modules]
left = [ "Workspaces" ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", "Settings", "Privacy", "Clock", "Tray" ]

[workspaces]
visibility_mode = "MonitorSpecific"
enable_workspace_filling = true

[window_title]
truncate_title_after_length = 100

[system_info]
indicators = ["Cpu", "Memory"]

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 60
alert_threshold = 80

[system_info.disk]
warn_threshold = 80
alert_threshold = 90

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80
sensor = "acpitz temp1"

[settings]
shutdown_cmd = "spm -p"
suspend_cmd = "spm -s"
hibernate_cmd = "spm -h"
reboot_cmd = "spm -r"
logout_cmd = "loginctl kill-user $(whoami)"
battery_format = "IconAndPercentage"
peripheral_battery_format = "Icon"
peripheral_indicators = { Specific = ["Headphones"] }
indicators = ["IdleInhibitor", "PowerProfile", "Audio", "Bluetooth", "Network", "Vpn", "Battery", "PeripheralBattery"]
remove_airplane_btn = true
remove_idle_btn = true

[clock]
format = "%a %d %b %T"

[appearance]
style = "Islands"
font = "Jetbrains Mono Nerd Font"
success_color = "#a6e3a1"
text_color = "#cdd6f4"

workspace_colors = [ "#fab387", "#b4befe", "#cba6f7" ]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"
