general.live_config_reload = true

general.import = [
	"~/.config/alacritty/themes/themes/breeze.toml"
]

[env]
term = "xterm-256color"

[window]
dimensions = { columns = 135, lines = 33 }
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "Dark"

[font]
normal = { family = "Hack", style = "Regular" }
bold = { family = "Hack" }
italic = { family = "Hack" }
bold_italic = { family = "Hack" }
size = 12.5

[colors]
primary.background = "#241F31"

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 500

[scrolling]
history = 65535
